### ISSUE TITLE
Abstract In Response

### ISSUE THREAD

**Issue by DavidDave99** [swkim101/cspapers.org#10]
Just tested the API, how can one access the abstract from the API response?

**Comment by swkim101** [comment]
You can retrieve abstract here: `https://raw.githubusercontent.com/swkim101/cspapers.org/main/{index}`

e.g., 

```
https://raw.githubusercontent.com/swkim101/cspapers.org/main/index2/2022/sp/Formal Model-Driven Discovery of Bluetooth Protocol Design Vulnerabilities
```

If 404, there is no abstract
