### ISSUE TITLE
Google scholar link in API

### ISSUE THREAD

**Issue by DavidDave99** [swkim101/cspapers.org#9]
Is there a way to return the google scholar link with the API? It would be a good addition to the API to have complete information.

**Comment by swkim101** [comment]
I understand this, but I want to minimize API traffic.  
The Google Scholar link is simply appending a paper title to a URL:
`https://scholar.google.com/scholar?q={title}`

**Comment by DavidDave99** [comment]
Ah okay makes sense. Thank you
